### ISSUE TITLE
欢迎加群讨论～

### ISSUE THREAD

**Issue by PengJiyuan** [arco-design/arco-design#14]
飞书群：

![lark 群](https://user-images.githubusercontent.com/19399269/138840525-aa3ffd5e-19c4-4de7-90cf-9cdf003012b8.png)

**Comment by taosiqi** [comment]
> 这个组件库跟其他组件库比（比如antd）有什么优势么？用户为什么要用这个新出的呢？相比之下发展时间更久的岂不是更稳定？

新的意味着 更多的可能

**Comment by likunyan** [comment]
我觉得挺好的，支持，我用 Material-UI 很久了，从0.x.x 开始用的，我都想换 arco 了，组件多，也很规范，antd 我觉得文档比较乱（个人觉得），可能我是后端吧，比较适合 Bootstrap 这种简单的。

**Comment by PengJiyuan** [comment]
> 我觉得挺好的，支持，我用 Material-UI 很久了，从0.x.x 开始用的，我都想换 arco 了，组件多，也很规范，antd 我觉得文档比较乱（个人觉得），可能我是后端吧，比较适合 Bootstrap 类似这种简单的。

谢谢认可，arco 在字节内部已经支持了 4000+ 的项目，可以放心使用哈，有问题随时反馈～

**Comment by mode365Dong** [comment]
受限于网关，我没法访问文档链接，怎么将文档本地化。谢谢

**Comment by PengJiyuan** [comment]
> 

额，什么意思，你访问不了 arco.design 吗？为啥

**Comment by Tenodec** [comment]
@PengJiyuan 应该是内网网络策略限制了的，建议github上放一个开发文档，这样可以内网部署

**Comment by PengJiyuan** [comment]
> @PengJiyuan 应该是内网网络策略限制了的，建议github上放一个开发文档，这样可以内网部署

开发文档就在这个仓库里，`yarn run dev:site` 即可

**Comment by hqz1989** [comment]
yarn run dev:site会报：
TypeError: Cannot read properties of undefined (reading 'lang')                    
    at getMetaFromMd (M:\ray-design\arco-design\site\node_modules\@arco-design\arco-markdown-loader\lib\getMeta.js:94:66)                  
    at M:\ray-design\arco-design\site\node_modules\@arco-design\arco-markdown-loader\lib\getMeta.js:114:20                                 
    at Array.map (<anonymous>)                                                                                                             
    at default_1 (M:\ray-design\arco-design\site\node_modules\@arco-design\arco-markdown-loader\lib\getMeta.js:111:28)                     
    at compileDemo (M:\ray-design\arco-design\site\node_modules\@arco-design\arco-markdown-loader\lib\compiler\demo.js:116:44)             
    at Object.loaderForArcoComponentDoc (M:\ray-design\arco-design\site\node_modules\@arco-design\arco-markdown-loader\lib\index.js:43:34) 
    at Object.default_1 (M:\ray-design\arco-design\site\node_modules\@arco-design\arco-markdown-loader\lib\index.js:184:37)                
    at LOADER_EXECUTION (M:\ray-design\arco-design\node_modules\loader-runner\lib\LoaderRunner.js:119:14)                                  
    at runSyncOrAsync (M:\ray-design\arco-design\node_modules\loader-runner\lib\LoaderRunner.js:120:4)                                     
    at iterateNormalLoaders (M:\ray-design\arco-design\node_modules\loader-runner\lib\LoaderRunner.js:232:2)    
还有：
Module not found: Error: Can't resolve '@arco-design/web-react' ……这样的很多。

希望能解答！
