### ISSUE TITLE
yarn start report error: Cannot read properties of undefined (reading 'lang')

### ISSUE THREAD

**Issue by luckyship** [arco-design/arco-design#1489]
- [X] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/web-react@2.40.2
- **Browser:** chrome106.0.0.0

## Extra info
i see the issue: https://github.com/arco-design/arco-design/issues/669
it provides solution to change git config to solve this, but it may affect other code in my computer.
can solve it in `arco-markdown-loader`? i can't find the repo in github.
if it's open souce, can provide it repo url, i'd like to create pr to solve it.

```
TypeError: Cannot read properties of undefined (reading 'lang')
at getMetaFromMd (M:\arco-design\site\node_modules@arco-design\arco-markdown-loader\lib\getMeta.js:94:66)
at M:\arco-design\site\node_modules@arco-design\arco-markdown-loader\lib\getMeta.js:114:20
at Array.map ()
at default_1 (M:\arco-design\site\node_modules@arco-design\arco-markdown-loader\lib\getMeta.js:111:28)
at compileDemo (M:\arco-design\site\node_modules@arco-design\arco-markdown-loader\lib\compiler\demo.js:116:44)
at Object.loaderForArcoComponentDoc (M:\arco-design\site\node_modules@arco-design\arco-markdown-loader\lib\index.js:43:34)
at Object.default_1 (M:\arco-design\site\node_modules@arco-design\arco-markdown-loader\lib\index.js:184:37)
at LOADER_EXECUTION (M:\arco-design\node_modules\loader-runner\lib\LoaderRunner.js:119:14)
at runSyncOrAsync (M:\arco-design\node_modules\loader-runner\lib\LoaderRunner.js:120:4)
at iterateNormalLoaders (M:\arco-design\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
```

## What is expected?
need to yarn start normally

**Comment by MisterLuffy** [comment]
The repo of arco-markdown-loader is [here](https://github.com/arco-design/arco-cli/blob/main/packages/arco-markdown-loader/src/getMeta.ts). PR is welcomed ❤️
