### ISSUE TITLE
@arco-plugins/unplugin-react 插件用不了

### ISSUE THREAD

**Issue by ljianc** [arco-design/arco-design#2729]
插件用到了builtins.pluginImport，可是最新版本的rspack已经删掉了这个配置。

TypeError: Cannot read properties of undefined (reading 'pluginImport')
[0]     at ImportPlugin.apply (D:\src\web\goodpc\node_modules\@arco-plugins\unplugin-react\lib\plugins\import.js:12:42)
[0]     at ArcoDesignPlugin.apply (D:\src\web\goodpc\node_modules\@arco-plugins\unplugin-react\lib\index.js:15:49)
[0]     at createCompiler (D:\src\web\goodpc\node_modules\@rspack\core\dist\rspack.js:54:24)
[0]     at create (D:\src\web\goodpc\node_modules\@rspack\core\dist\rspack.js:89:26)
[0]     at rspack (D:\src\web\goodpc\node_modules\@rspack\core\dist\rspack.js:115:37)
[0]     at RspackCLI.createCompiler (D:\src\web\goodpc\node_modules\@rspack\cli\dist\rspack-cli.js:66:34)
[0]     at async Object.handler (D:\src\web\goodpc\node_modules\@rspack\cli\dist\commands\serve.js:25:30)
![1719557622933](https://github.com/arco-design/arco-design/assets/10055508/74e83a4f-e06f-4195-a7fd-a524d554bcba)

**Comment by yinkaihui** [comment]
2.0.0-beta.x 最新的 beta 版本
