### ISSUE TITLE
Could not work with next@4.2.x

### ISSUE THREAD

**Issue by taoqf** [arco-design/arco-design#2730]
我在项目中重度使用了这个组件库，但现在跟next4.2的版本结合使用存在很多问题，非常非常多，但也可能根本原因只有一个，能不能查一下具体是什么原因导致的。基本上错误类似于这样

```log
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
 ⨯ Internal error: TypeError: Cannot read properties of null (reading 'useContext')
    at useContext (/app/node_modules/react/cjs/react.development.js:1618:21)
    at Upload (/app/node_modules/@arco-design/web-react/lib/Upload/upload.js:106:37)
```

**Comment by taoqf** [comment]
Bye.
