### ISSUE TITLE
React19 中无法使用 Message/Notification

### ISSUE THREAD

**Issue by miss85246** [arco-design/arco-design#2900]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design/issues)

## 基本信息 
- **依赖包名 及 版本:** @arco-design/web-react@2.65.0
- **框架版本:** React
- **浏览器版本:** Microsoft Edge 版本 131.0.2903.99 (正式版本) (arm64)
- **复现地址:** https://codesandbox.io/p/sandbox/exciting-joana-qtv2fs?file=%2Fdemo.js&workspaceId=ws_EeJXDn9XhMqfEdRnCrZmQD

## 复现步骤
任意位置使用 Message.info 或者 Notification.info 会出现报错提示， 提示 CopyReactDOM.render is not a function

**Comment by shen774411223d** [comment]
怎么感觉现在arco-design还没有全面支持react19，升级完react之后一大堆组件错误

**Comment by yi-boide** [comment]
同样的问题，也没有解决的？

**Comment by miss85246** [comment]
等官方适配吧，已经降级到 R18了

**Comment by shen774411223d** [comment]
> 等官方适配吧，已经降级到 R18了

官方看着一直不回复，感觉遥遥无期啊

**Comment by miss85246** [comment]
> > 等官方适配吧，已经降级到 R18了
> 
> 官方看着一直不回复，感觉遥遥无期啊

总得给人家留点时间不是？更何况快过年了，得让人家过个好年回来了再说啊🤔🤔🤔

**Comment by Tenodec** [comment]
感觉咋不关注了呢，这个项目是不是停摆了啊.semi 都安排了，antd 更快，去年就支持了。说到底还是react 18用了老api的缘故，antd 用的react18的api 所以改插件很快，总不能18的api 19就全部不支持了吧。

**Comment by xzysun** [comment]
> 在最新的@arco-design/web-react@2.66.0中依然出现(React19) 复现地址: https://codesandbox.io/p/sandbox/sharp-ritchie-lzwp65?file=%2Fsrc%2Findex.tsx%3A4%2C25 [@yinkaihui](https://github.com/yinkaihui)

@SmallL-U  需要在入口文件引入那个adapter

```import '@arco-design/web-react/es/_util/react-19-adapter';```

**Comment by SmallL-U** [comment]
> > 在最新的@arco-design/web-react@2.66.0中依然出现(React19) 复现地址: https://codesandbox.io/p/sandbox/sharp-ritchie-lzwp65?file=%2Fsrc%2Findex.tsx%3A4%2C25 [@yinkaihui](https://github.com/yinkaihui)
> 
> [@SmallL-U](https://github.com/SmallL-U) 需要在入口文件引入那个adapter
> 
> `import '@arco-design/web-react/es/_util/react-19-adapter';`

OK，感谢

**Comment by lokalius** [comment]
依然存在报错：
```text
Uncaught (in promise) TypeError: CopyReactDOM.render is not a function
    at copyRender (react-dom.js:40:1)
    at render (react-dom.js:114:1)
    at index.js:182:1
    at new Promise (<anonymous>)
    at Function.addInstance (index.js:181:1)
    at Function.info (index.js:200:1)
    at census.tsx:53:1
```

出错代码在：
```typescript
Notification.warning({
  closable: false,
  title: 'Notification',
  content: data?.msg
})
```
> 已经引入`import '@arco-design/web-react/es/_util/react-19-adapter'`

版本信息：
```json
"@arco-design/web-react": "^2.66.1",
"react": "^19.1.0",
"react-dom": "^19.1.0"
```

**Comment by Shunjun** [comment]
> 依然存在报错：
> 
> ```
> Uncaught (in promise) TypeError: CopyReactDOM.render is not a function
>     at copyRender (react-dom.js:40:1)
>     at render (react-dom.js:114:1)
>     at index.js:182:1
>     at new Promise (<anonymous>)
>     at Function.addInstance (index.js:181:1)
>     at Function.info (index.js:200:1)
>     at census.tsx:53:1
> ```
> 
> 出错代码在：
> 
> Notification.warning({
>   closable: false,
>   title: 'Notification',
>   content: data?.msg
> })
> > 已经引入`import '@arco-design/web-react/es/_util/react-19-adapter'`
> 
> 版本信息：
> 
> "@arco-design/web-react": "^2.66.1",
> "react": "^19.1.0",
> "react-dom": "^19.1.0"

看下  '@arco-design/web-react/es/_util/react-19-adapter' 是不是被 tree-shake 掉了

**Comment by zhemuse** [comment]
https://arco.design/react/docs/start#%E5%85%BC%E5%AE%B9-react-19
